### ISSUE TITLE
Compilation of http_wrapper fails with boost >= 1.66.0

### ISSUE THREAD

**Issue by krypt-n** [VROOM-Project/vroom#297]
Hi,

I just tried to compile the current master branch on my system and it appears that `routing/http_wrapper.cpp` doesn't compile with boost 1.66.0 or newer, since [this](https://github.com/VROOM-Project/vroom/blob/ebda715a30b4526275d1c634b415b6ada51e923a/src/routing/http_wrapper.cpp#L78) deprecated constructor was removed. (Compare docs for [1.65](https://www.boost.org/doc/libs/1_65_0/doc/html/boost_asio/reference/ssl__context/context.html) and [1.66](https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/ssl__context/context.html)).

```
routing/http_wrapper.cpp: In member function ‘std::string vroom::routing::HttpWrapper::ssl_send_then_receive(const string&) const’:
routing/http_wrapper.cpp:79:71: error: no matching function for call to ‘boost::asio::ssl::context::context(boost::asio::io_service&, boost::asio::ssl::context_base::method)’
   79 |       ctx(io_service, boost::asio::ssl::context::method::sslv23_client);
      |                                                                       ^
```

I didn't look into a possible fix for this problem, just wanted to let you know.

**Comment by jcoupey** [comment]
Thanks for this quick feedback. I've indeed only tested this with boost 1.65.

**Comment by jcoupey** [comment]
OK, it seems that the first argument is just not used at all any more.

@krypt-n I don't have a 1.66 boost install out of the box, would you mind checking if this patch solves the compilation problem on 1.66?

```patch
diff --git a/src/routing/http_wrapper.cpp b/src/routing/http_wrapper.cpp
index 32eb052..c4b0596 100644
--- a/src/routing/http_wrapper.cpp
+++ b/src/routing/http_wrapper.cpp
@@ -75,8 +75,8 @@ std::string HttpWrapper::ssl_send_then_receive(const std::string& query) const {
   try {
     boost::asio::io_service io_service;
 
-    boost::asio::ssl::context
-      ctx(io_service, boost::asio::ssl::context::method::sslv23_client);
+    boost::asio::ssl::context ctx(
+      boost::asio::ssl::context::method::sslv23_client);
     boost::asio::ssl::stream<boost::asio::ip::tcp::socket> ssock(io_service,
                                                                  ctx);
```

**Comment by krypt-n** [comment]
Yep, it solves the problem for boost 1.72.0 (and I assume everything in between)

**Comment by jcoupey** [comment]
@krypt-n thanks for the handcrafted CI builds! ;-)
